---
title: "*C*omplexity *r*educes feed*i*ng s*t*reng*t*h of fr*e*shwater p*r*edators (CRITTER, Code Repository)"
bibliography: references/CRITTERcode.bib
csl: references/methods-in-ecology-and-evolution.csl
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

This code is a supplement to the upcoming publication of Aranbarri et al. (unpublished) investigating the effect of habitat complexity on the feeding functional response of two freshwater invertebrate predators. You will find details on the methodology in the cited publication. We will link to it after we make it publicly available.

**Note that this code is still under construction!**

## License

This code is published under a [**GNU General Public License 3**](https://www.gnu.org/licenses/gpl-3.0.html).

## Authors

-   Björn C. Rall ([0000-0002-3191-8389](https://orcid.org/0000-0002-3191-8389))
    -   [bjoern.rall@uni-konstanz.de](bjoern.rall@uni-konstanz.de)
    -   Aquatic Ecology and Evolution Group, Limnological Institute, University of Konstanz, Mainaustraße 252, 78464 Konstanz/Egg, Germany
-   Mireia Aranbarri ([0009-0001-3506-0914](https://orcid.org/0009-0001-3506-0914))
    -   [mireia.arambarri@ehu.eus](mireia.arambarri@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Lorea Flores ([0000-0002-0082-4072](https://orcid.org/0000-0002-0082-4072))
    -   [lflorescompains@gmail.com](lflorescompains@gmail.com)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Ioar de Guzmán ([0000-0001-8894-8477](https://orcid.org/0000-0001-8894-8477))
    -   [mirenioar.deguzman@ehu.eus](mirenioar.deguzman@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Aitor Larrañaga ([0000-0002-0185-9154](https://orcid.org/0000-0002-0185-9154))
    -   [aitor.larranagaa@ehu.eus](aitor.larranagaa@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Julia Reiss ([0000-0002-3740-0046](https://orcid.org/0000-0002-3740-0046))
    -   [julia.reiss@brunel.ac.uk](julia.reiss@brunel.ac.uk)
    -   Division of Environmental Sciences, College of Health, Medicine and Life Sciences, Brunel University of London, Uxbridge, UB8 3PH, UK

## Related Works

-   [Data on Zenodo](https://doi.org/10.5281/zenodo.14891980) [@FloresEtAl2025ComplexityReducesFeedingData]

-   [Data on GitHub](https://github.com/b-c-r/CRITTERdata)

-   [R-Code on Zenodo](https://doi.org/10.5281/zenodo.14894598) [@RallEtAl2025ComplexityReducesFeedingCode]

-   [R-Code on GitHub](https://github.com/b-c-r/CRITTERdata)

-   [Statistical Report on GitHub](https://github.com/b-c-r/CRITTERstatistics)

-   Statistical Report on Zenodo (link tba)

-   Scientific Preprint Paper (link tba)

## Brief Code Description

We predominantly used functions to organize our R code for this project. Each function is saved in a separate \*.R-file and documented approximately in roxygen2 style [@WickhamEtAl2024Roxygen2InLineDocumentation]. The functions depend mostly hierarchically on each other. All functions are saved in the project's sub folder called functions_*.

### Phenomenological Functional Response Type Test

The functions are located in `/functions_phen_test/`.

**`phen_type_test`** is a wrapper around the function `frair_test` [@PritchardEtAl2017FrairToolsFunctional; @PritchardEtAl2017FrairPackageFitting] to test for the type of the functional response using the proportion of prey eaten as response to the initial prey density. If the proportion of prey eaten increases at low prey densities and decreases after reaching a maximum, there is evidence for a type III functional response [@Juliano2001NonlinearCurveFitting]. Proportion data is fitted using a binomial GLM, but see @Crawley2012Book, chapter 16 for an introduction to this topic.

Required packages and their dependencies to be installed:

- `dplyr` [@WickhamEtAl2023DplyrGrammarData]
- `purrr` [@WickhamHenry2025PurrrFunctionalProgramming]
- `foreach` [@MicrosoftWeston2022ForeachProvidesForeach]
- `frair` [@PritchardEtAl2017FrairToolsFunctional]

Required packages to be attached:

- `dplyr` [@WickhamEtAl2023DplyrGrammarData]
- `foreach` [@MicrosoftWeston2022ForeachProvidesForeach]

**`phen_type_table`** takes a `phen_type_test` output and creates a nice table for the statistical report. Note that the function uses options from `kableEXTRA` [@Zhu2024KableExtraConstructComplex] that will only work for LaTeX/PDF outputs. This function is rather hard-coded and only useful in the CRITTER project.

Required packages and their dependencies to be installed:

- `foreach` [@MicrosoftWeston2022ForeachProvidesForeach]
- `kableExtra` [@Zhu2024KableExtraConstructComplex]

Required packages to be attached:

- `foreach` [@MicrosoftWeston2022ForeachProvidesForeach]

## Funding Information

-   Mireia Aranbarri was funded by the **Investigo Programm funded by the NextGenerationEU initiative**.
-   Lorea Flores was funded by a grant by the **Spanish Ministry of Education and Culture**.
-   Ioar de Guzmán was funded by the **Spanish Ministry of Science, Innovation and Universities (TED2021-129966B-C31)**.
-   Julia Reiss was supported by a **Royal Society of London Starting Grant**.
-   Björn C. Rall gratefully acknowledges the funding by the **German Science Foundation (DFG) to the Research Unit DynaSym (FOR 5064)**.

## References
